"""
Django settings for abe_pte project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-kc&7(+$5aa0%zq!wj2&=)zkzuz^hpc!@_qx##w==-2jnh^&7_6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = ['82.112.226.176','admin.abepte.accoladesweb.com','localhost']


# Application definition

INSTALLED_APPS = [
    "unfold",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "mocktest",
    "examinor",
]

UNFOLD = {
    "SITE_TITLE": "ABE PTE Administration",
    "SITE_HEADER": "ABE PTE",
    "SITE_SUBHEADER": "Evaluation operations",
    "SITE_URL": "/admin/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "DASHBOARD_CALLBACK": "abe_pte.admin_dashboard.dashboard_callback",
    "STYLES": [lambda request: static("admin/css/theme.css")],
    "COLORS": {
        "base": {
            "50": "#f8fafc",
            "100": "#f1f5f9",
            "200": "#e5e7eb",
            "300": "#cbd5e1",
            "400": "#94a3b8",
            "500": "#64748b",
            "600": "#475569",
            "700": "#334155",
            "800": "#1e293b",
            "900": "#0f172a",
            "950": "#020617",
        },
        "primary": {
            "50": "#e8f8fe",
            "100": "#d0f1fd",
            "200": "#a5e3fa",
            "300": "#6fd2f6",
            "400": "#38c1f2",
            "500": "#14b3ef",
            "600": "#0e9ed6",
            "700": "#0b7fae",
            "800": "#0d668a",
            "900": "#104f69",
            "950": "#082f3f",
        },
        "font": {
            "subtle-light": "#94a3b8",
            "subtle-dark": "#94a3b8",
            "default-light": "#475569",
            "default-dark": "#cbd5e1",
            "important-light": "#1e293b",
            "important-dark": "#f8fafc",
        },
    },
    "COMMAND": {
        "search_models": True,
        "show_history": True,
    },
    "SIDEBAR": {
        "show_search": True,
        "command_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Operations"),
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Mock tests"),
                        "icon": "assignment",
                        "link": reverse_lazy("admin:mocktest_mocktest_changelist"),
                    },
                    {
                        "title": _("Test sessions"),
                        "icon": "history_edu",
                        "link": reverse_lazy("admin:mocktest_usermocktestsession_changelist"),
                        "badge": "abe_pte.admin_dashboard.incomplete_sessions_badge",
                    },
                    {
                        "title": _("User responses"),
                        "icon": "grading",
                        "link": reverse_lazy("admin:mocktest_userresponse_changelist"),
                        "badge": "abe_pte.admin_dashboard.failed_evaluations_badge",
                    },
                    {
                        "title": _("Single evaluations"),
                        "icon": "task_alt",
                        "link": reverse_lazy("admin:mocktest_singleresponse_changelist"),
                    },
                    {
                        "title": _("Evaluation cache"),
                        "icon": "cached",
                        "link": reverse_lazy("admin:examinor_evaluationcache_changelist"),
                    },
                ],
            },
            {
                "title": _("Question bank"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Questions"),
                        "icon": "quiz",
                        "link": reverse_lazy("admin:mocktest_question_changelist"),
                    },
                    {
                        "title": _("Subsections"),
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:mocktest_subsection_changelist"),
                    },
                    {
                        "title": _("Sections"),
                        "icon": "category",
                        "link": reverse_lazy("admin:mocktest_section_changelist"),
                    },
                    {
                        "title": _("Mock test sections"),
                        "icon": "view_module",
                        "link": reverse_lazy(
                            "admin:mocktest_mocktestsection_changelist"
                        ),
                    },
                    {
                        "title": _("Question options"),
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:mocktest_questionoption_changelist"),
                    },
                    {
                        "title": _("Blank definitions"),
                        "icon": "view_list",
                        "link": reverse_lazy("admin:mocktest_subquestion_changelist"),
                    },
                    {
                        "title": _("Rubrics"),
                        "icon": "rule",
                        "link": reverse_lazy("admin:mocktest_globalrubric_changelist"),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "abe_pte.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "abe_pte.wsgi.application"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_WHISPER_API_KEY = os.getenv("OPENAI_WHISPER_API_KEY")
OPENAI_TIMEOUT_SECONDS = float(os.getenv("OPENAI_TIMEOUT_SECONDS", "60"))
OPENAI_MAX_RETRIES = int(os.getenv("OPENAI_MAX_RETRIES", "2"))
OPENAI_EVALUATION_MODEL = os.getenv("OPENAI_EVALUATION_MODEL", "gpt-5-nano")
OPENAI_TRANSCRIPTION_MODEL = os.getenv("OPENAI_TRANSCRIPTION_MODEL", "whisper-1")

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# PostgreSQL for production
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.getenv("DB_NAME", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.getenv("DB_USER", ""),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", ""),
        "PORT": os.getenv("DB_PORT", ""),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# csrf
CSRF_TRUSTED_ORIGINS = [
    "https://admin.abepte.accoladesweb.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://abepte.accoladesweb.com",
    "https://pte.abeedu.com",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",
    "https://abepte.accoladesweb.com",
    "https://pte.abeedu.com",
]
CORS_ALLOW_HEADERS = list(default_headers) + [
    "timer-exceeded",
]
CORS_ALLOW_CREDENTIALS = True

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")
CELERY_TASK_DEFAULT_QUEUE = os.getenv("CELERY_TASK_DEFAULT_QUEUE", "default")
CELERY_EVALUATION_QUEUE = os.getenv("CELERY_EVALUATION_QUEUE", "evaluation")
CELERY_TRANSCRIPTION_QUEUE = os.getenv("CELERY_TRANSCRIPTION_QUEUE", "transcription")
CELERY_TASK_ACKS_LATE = os.getenv("CELERY_TASK_ACKS_LATE", "true").lower() == "true"
CELERY_TASK_REJECT_ON_WORKER_LOST = (
    os.getenv("CELERY_TASK_REJECT_ON_WORKER_LOST", "true").lower() == "true"
)
CELERY_WORKER_PREFETCH_MULTIPLIER = int(
    os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1")
)
CELERY_TASK_TRACK_STARTED = os.getenv("CELERY_TASK_TRACK_STARTED", "true").lower() == "true"
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "300"))
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "360"))
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": int(os.getenv("CELERY_VISIBILITY_TIMEOUT_SECONDS", "3600")),
}
EVALUATION_STALE_AFTER_MINUTES = int(
    os.getenv("EVALUATION_STALE_AFTER_MINUTES", "20")
)
EVALUATION_RECOVERY_BATCH_SIZE = int(
    os.getenv("EVALUATION_RECOVERY_BATCH_SIZE", "100")
)
EVALUATION_RECOVERY_INTERVAL_SECONDS = float(
    os.getenv("EVALUATION_RECOVERY_INTERVAL_SECONDS", "300")
)
CELERY_TASK_ROUTES = {
    "mocktest.tasks.evaluate_user_response": {"queue": CELERY_EVALUATION_QUEUE},
    "mocktest.tasks.evaluate_single_response": {"queue": CELERY_EVALUATION_QUEUE},
    "mocktest.tasks.transcribe_task": {"queue": CELERY_TRANSCRIPTION_QUEUE},
    "mocktest.tasks.transcribe_single_task": {"queue": CELERY_TRANSCRIPTION_QUEUE},
    "mocktest.tasks.recover_stale_evaluations": {"queue": CELERY_TASK_DEFAULT_QUEUE},
}
CELERY_BEAT_SCHEDULE = {
    "recover-stale-evaluations": {
        "task": "mocktest.tasks.recover_stale_evaluations",
        "schedule": EVALUATION_RECOVERY_INTERVAL_SECONDS,
    },
}

# CORS_ALLOW_ALL_ORIGINS = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "": {  # root logger
            "handlers": ["console"],
            "level": "WARNING",
        },
    },
}
